CREATE TABLE Driver
(
ID INT PRIMARY KEY NOT NULL,  
Driver_fio CHAR(50) NOT NULL
);

CREATE TABLE Station 
(
ID INT PRIMARY KEY NOT NULL, 
Station_name CHAR(50) NOT NULL
);

CREATE TABLE Town
(
ID INT PRIMARY KEY NOT NULL, 
Towm_name CHAR(50) NOT NULL
);

CREATE TABLE Bus
(
ID INT PRIMARY KEY NOT NULL, 
Bus_name CHAR(50) NOT NULL,
Gos_number CHAR(20) NOT NULL,
Driver_id INT NOT NULL,
FOREIGN KEY (Driver_id)  REFERENCES Driver (ID)
);

CREATE TABLE Route
(
ID INT PRIMARY KEY NOT NULL,   
Time_in CHAR(10) NOT NULL,
Time_out CHAR(10) NOT NULL,
Bus_id INT NOT NULL,
Town_id INT NOT NULL,
Station_id INT NOT NULL,
FOREIGN KEY (Bus_id)  REFERENCES Bus (ID),
FOREIGN KEY (Town_id)  REFERENCES Town (ID),
FOREIGN KEY (Station_id)  REFERENCES Station (ID)
);
